-- Direct Promocoes - schema completo do Supabase
-- Pode ser executado em um projeto novo ou em uma instalacao existente.

begin;

create table if not exists public.diaristas (
  id text primary key,
  name text not null,
  phone text,
  cpf text,
  neighborhood text,
  sectors text,
  status text default 'Ativa',
  created_at timestamptz default now()
);

create table if not exists public.lojas_redes (
  id text primary key,
  name text not null,
  network text,
  type text,
  owner text,
  city text,
  address text,
  health text default 'Alta',
  created_at timestamptz default now()
);

create table if not exists public.demandas (
  id text primary key,
  store_id text references public.lojas_redes(id) on delete cascade,
  date date,
  end_date date,
  start_time time default '08:00',
  sector text,
  spots integer default 1,
  daily_rate numeric(12, 2) default 0,
  worker_cost numeric(12, 2) default 0,
  assigned_diarist_ids jsonb default '[]'::jsonb,
  status text default 'Aberta',
  created_at timestamptz default now()
);

create table if not exists public.setores (
  id text primary key,
  name text not null unique,
  created_at timestamptz default now()
);

create table if not exists public.diarias_setor (
  id text primary key,
  sector text not null,
  min_value numeric(12, 2) default 0,
  max_value numeric(12, 2) default 0,
  created_at timestamptz default now()
);

create table if not exists public.diarias_empresas (
  id text primary key,
  company text not null,
  value numeric(12, 2) default 0,
  created_at timestamptz default now()
);

create table if not exists public.registros_financeiros (
  id text primary key,
  diarist_id text references public.diaristas(id) on delete set null,
  diarist_name text not null,
  store text not null,
  date date not null,
  start_time time,
  end_time time,
  sector text,
  daily_value numeric(12, 2) default 0,
  transport numeric(12, 2) default 0,
  advance numeric(12, 2) default 0,
  extra_costs numeric(12, 2) default 0,
  paid boolean default false,
  paid_at timestamptz,
  notes text,
  created_at timestamptz default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'operador' check (role in ('admin', 'financeiro', 'rh', 'operador')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.access_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event text not null check (event in ('login', 'logout')),
  user_agent text,
  created_at timestamptz default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  table_name text not null,
  record_id text,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz default now()
);

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), 'operador');
$$;

create or replace function public.can_view_finance()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_app_role() in ('admin', 'financeiro');
$$;

create or replace function public.can_view_full_cpf()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_app_role() in ('admin', 'rh');
$$;

create or replace function public.is_valid_cpf(value text)
returns boolean
language plpgsql
immutable
as $$
declare
  digits text := regexp_replace(coalesce(value, ''), '[^0-9]', '', 'g');
  total integer;
  digit integer;
  index integer;
begin
  if length(digits) <> 11
     or digits ~ '^([0-9])\1{10}$'
     or digits in ('01234567890', '12345678909', '98765432100')
  then return false; end if;
  total := 0;
  for index in 1..9 loop total := total + substring(digits, index, 1)::integer * (11 - index); end loop;
  digit := (total * 10) % 11;
  if digit = 10 then digit := 0; end if;
  if digit <> substring(digits, 10, 1)::integer then return false; end if;
  total := 0;
  for index in 1..10 loop total := total + substring(digits, index, 1)::integer * (12 - index); end loop;
  digit := (total * 10) % 11;
  if digit = 10 then digit := 0; end if;
  return digit = substring(digits, 11, 1)::integer;
end;
$$;

create or replace function public.is_valid_phone(value text)
returns boolean
language sql
immutable
as $$
  with normalized as (select regexp_replace(coalesce(value, ''), '[^0-9]', '', 'g') as digits)
  select length(digits) in (10, 11)
    and left(digits, 2) <> '00'
    and (length(digits) = 10 or substring(digits, 3, 1) = '9')
  from normalized;
$$;

-- A validacao por trigger preserva registros legados, mas bloqueia dados
-- invalidos em novos cadastros ou quando CPF/telefone forem alterados.
alter table public.diaristas drop constraint if exists diaristas_valid_cpf;
alter table public.diaristas drop constraint if exists diaristas_valid_phone;

insert into public.profiles (id, email, role)
select id, email, 'operador'
from auth.users
on conflict (id) do nothing;

insert into public.profiles (id, email, role)
select id, email, 'admin'
from auth.users
where lower(email) = 'marcosvinidirect@gmail.com'
on conflict (id) do update set email = excluded.email, role = 'admin', updated_at = now();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'operador')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists create_app_profile on auth.users;
create trigger create_app_profile
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.log_app_access(event_name text, client_user_agent text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or event_name not in ('login', 'logout') then
    raise exception 'Evento de acesso invalido';
  end if;
  insert into public.access_logs (user_id, event, user_agent)
  values (auth.uid(), event_name, left(client_user_agent, 500));
end;
$$;

create or replace function public.write_audit_log()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.audit_logs (user_id, table_name, record_id, action, old_data, new_data)
  values (
    auth.uid(),
    tg_table_name,
    case when tg_op = 'DELETE' then old.id::text else new.id::text end,
    tg_op,
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) end
  );
  return coalesce(new, old);
end;
$$;

create or replace function public.protect_diarist_cpf()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    if not public.is_valid_cpf(new.cpf) then raise exception 'CPF invalido'; end if;
    if not public.is_valid_phone(new.phone) then raise exception 'Telefone invalido'; end if;
  else
    if old.cpf is distinct from new.cpf and not public.is_valid_cpf(new.cpf) then
      raise exception 'CPF invalido';
    end if;
    if old.phone is distinct from new.phone and not public.is_valid_phone(new.phone) then
      raise exception 'Telefone invalido';
    end if;
    if old.cpf is distinct from new.cpf and not public.can_view_full_cpf() then
      raise exception 'Sem permissao para alterar CPF';
    end if;
  end if;
  return new;
end;
$$;

create or replace function public.upsert_diarista(payload jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_cpf text;
  supplied_cpf text := nullif(payload ->> 'cpf', '');
begin
  if auth.uid() is null then raise exception 'Autenticacao obrigatoria'; end if;
  if supplied_cpf like '%*%' then supplied_cpf := null; end if;
  select cpf into existing_cpf from public.diaristas where id = payload ->> 'id';

  if existing_cpf is not null and supplied_cpf is not null
     and existing_cpf is distinct from supplied_cpf and not public.can_view_full_cpf() then
    raise exception 'Sem permissao para alterar CPF';
  end if;

  insert into public.diaristas (id, name, phone, cpf, neighborhood, sectors, status)
  values (
    payload ->> 'id', payload ->> 'name', payload ->> 'phone',
    coalesce(supplied_cpf, existing_cpf), payload ->> 'neighborhood',
    payload ->> 'sectors', coalesce(payload ->> 'status', 'Ativa')
  )
  on conflict (id) do update set
    name = excluded.name,
    phone = excluded.phone,
    cpf = coalesce(supplied_cpf, public.diaristas.cpf),
    neighborhood = excluded.neighborhood,
    sectors = excluded.sectors,
    status = excluded.status;
end;
$$;

-- Compatibilidade com bancos criados por versoes anteriores do schema.
alter table public.diaristas
  add column if not exists neighborhood text;

alter table public.demandas
  add column if not exists end_date date,
  add column if not exists start_time time default '08:00';

update public.demandas
set end_date = date
where end_date is null;

update public.demandas
set start_time = '08:00'
where start_time is null;

create index if not exists demandas_store_id_idx
  on public.demandas (store_id);
create index if not exists demandas_date_idx
  on public.demandas (date);
create index if not exists demandas_status_idx
  on public.demandas (status);
create index if not exists registros_financeiros_diarist_id_idx
  on public.registros_financeiros (diarist_id);
create index if not exists registros_financeiros_date_idx
  on public.registros_financeiros (date);
create index if not exists registros_financeiros_paid_idx
  on public.registros_financeiros (paid);

create index if not exists audit_logs_created_at_idx
  on public.audit_logs (created_at desc);
create index if not exists access_logs_created_at_idx
  on public.access_logs (created_at desc);

create or replace view public.diaristas_masked
with (security_barrier = true)
as
select
  id,
  name,
  phone,
  case
    when cpf is null then null
    else '***.***.***-' || right(regexp_replace(cpf, '[^0-9]', '', 'g'), 2)
  end as cpf,
  neighborhood,
  sectors,
  status,
  created_at
from public.diaristas;

grant select on public.diaristas_masked to authenticated;

do $$
declare
  audited_table text;
begin
  foreach audited_table in array array[
    'diaristas', 'lojas_redes', 'demandas', 'setores',
    'diarias_setor', 'diarias_empresas', 'registros_financeiros', 'profiles'
  ] loop
    execute format('drop trigger if exists audit_changes on public.%I', audited_table);
    execute format(
      'create trigger audit_changes after insert or update or delete on public.%I for each row execute function public.write_audit_log()',
      audited_table
    );
  end loop;
end;
$$;

drop trigger if exists protect_cpf_changes on public.diaristas;
create trigger protect_cpf_changes
before insert or update of cpf, phone on public.diaristas
for each row execute function public.protect_diarist_cpf();

alter table public.diaristas enable row level security;
alter table public.lojas_redes enable row level security;
alter table public.demandas enable row level security;
alter table public.setores enable row level security;
alter table public.diarias_setor enable row level security;
alter table public.diarias_empresas enable row level security;
alter table public.registros_financeiros enable row level security;
alter table public.profiles enable row level security;
alter table public.access_logs enable row level security;
alter table public.audit_logs enable row level security;

-- Remove politicas anonimas antigas. O SaaS exige login do Supabase Auth.
drop policy if exists "anon_select_diaristas" on public.diaristas;
drop policy if exists "anon_insert_diaristas" on public.diaristas;
drop policy if exists "anon_update_diaristas" on public.diaristas;
drop policy if exists "anon_delete_diaristas" on public.diaristas;
drop policy if exists "anon_select_lojas_redes" on public.lojas_redes;
drop policy if exists "anon_insert_lojas_redes" on public.lojas_redes;
drop policy if exists "anon_update_lojas_redes" on public.lojas_redes;
drop policy if exists "anon_delete_lojas_redes" on public.lojas_redes;
drop policy if exists "anon_select_demandas" on public.demandas;
drop policy if exists "anon_insert_demandas" on public.demandas;
drop policy if exists "anon_update_demandas" on public.demandas;
drop policy if exists "anon_delete_demandas" on public.demandas;
drop policy if exists "anon_select_setores" on public.setores;
drop policy if exists "anon_insert_setores" on public.setores;
drop policy if exists "anon_update_setores" on public.setores;
drop policy if exists "anon_delete_setores" on public.setores;
drop policy if exists "anon_select_diarias_setor" on public.diarias_setor;
drop policy if exists "anon_insert_diarias_setor" on public.diarias_setor;
drop policy if exists "anon_update_diarias_setor" on public.diarias_setor;
drop policy if exists "anon_delete_diarias_setor" on public.diarias_setor;
drop policy if exists "anon_select_diarias_empresas" on public.diarias_empresas;
drop policy if exists "anon_insert_diarias_empresas" on public.diarias_empresas;
drop policy if exists "anon_update_diarias_empresas" on public.diarias_empresas;
drop policy if exists "anon_delete_diarias_empresas" on public.diarias_empresas;

drop policy if exists "auth_manage_diaristas" on public.diaristas;
drop policy if exists "auth_select_full_diaristas" on public.diaristas;
drop policy if exists "auth_insert_diaristas" on public.diaristas;
drop policy if exists "auth_update_diaristas" on public.diaristas;
create policy "auth_select_full_diaristas"
  on public.diaristas for select to authenticated using (public.can_view_full_cpf());
create policy "auth_insert_diaristas"
  on public.diaristas for insert to authenticated with check (true);
create policy "auth_update_diaristas"
  on public.diaristas for update to authenticated using (true) with check (true);

drop policy if exists "auth_manage_lojas_redes" on public.lojas_redes;
create policy "auth_manage_lojas_redes"
  on public.lojas_redes for all to authenticated using (true) with check (true);

drop policy if exists "auth_manage_demandas" on public.demandas;
create policy "auth_manage_demandas"
  on public.demandas for all to authenticated using (true) with check (true);

drop policy if exists "auth_manage_setores" on public.setores;
create policy "auth_manage_setores"
  on public.setores for all to authenticated using (true) with check (true);

drop policy if exists "auth_manage_diarias_setor" on public.diarias_setor;
create policy "auth_manage_diarias_setor"
  on public.diarias_setor for all to authenticated using (true) with check (true);

drop policy if exists "auth_manage_diarias_empresas" on public.diarias_empresas;
create policy "auth_manage_diarias_empresas"
  on public.diarias_empresas for all to authenticated using (true) with check (true);

drop policy if exists "auth_manage_registros_financeiros" on public.registros_financeiros;
create policy "auth_manage_registros_financeiros"
  on public.registros_financeiros for all to authenticated
  using (public.can_view_finance()) with check (public.can_view_finance());

drop policy if exists "auth_read_profiles" on public.profiles;
drop policy if exists "admin_manage_profiles" on public.profiles;
create policy "auth_read_profiles"
  on public.profiles for select to authenticated
  using (id = auth.uid() or public.current_app_role() = 'admin');
create policy "admin_manage_profiles"
  on public.profiles for all to authenticated
  using (public.current_app_role() = 'admin')
  with check (public.current_app_role() = 'admin');

drop policy if exists "admin_read_access_logs" on public.access_logs;
create policy "admin_read_access_logs"
  on public.access_logs for select to authenticated
  using (public.current_app_role() = 'admin');

drop policy if exists "admin_read_audit_logs" on public.audit_logs;
create policy "admin_read_audit_logs"
  on public.audit_logs for select to authenticated
  using (public.current_app_role() = 'admin');

revoke all on function public.log_app_access(text, text) from public;
grant execute on function public.log_app_access(text, text) to authenticated;
revoke all on function public.upsert_diarista(jsonb) from public;
grant execute on function public.upsert_diarista(jsonb) to authenticated;

commit;
